### PR TITLE
WIP: Typescript

### PR DESCRIPTION
**Pull request by charliewilco**
- [ ] Converts setup from Babel to TypeScript
- [ ] Migrates Jasmine / Karma / Browserify to Jest with TypeScript
- [ ] Uses Prettier for code formatting over eslint

TODO:

- [ ] Correct all type errors
- [ ] Passing tests
- [ ] Add generated typings to `package.json`

### CODE REVIEW

**Comment by Rosey** [comment]
Thanks for getting this started! Question: did we need to convert all single quotes to double quotes? It feels like the js community generally prefers single quotes for strings so I liked sticking with that standard 😊

**Comment by charliewilco** [comment]
not at all! double quotes are just prettier's default. switched it up

**Comment by yurist38** [comment]
Hello! Do you guys plan to move it forward? I just used this package in TS project, have written type definitions inside my project for now. So I'm wondering if you are still planning to convert it to TS. Or if it's not going forward should I open a PR with `.d.ts` file instead?

**Comment by charliewilco** [comment]
i actually haven't had time to come back to this.

**Pull request closed without merging**
