### PR TITLE
Render preserved new lines after list correctly

### PR DESCRIPTION
**Pull request by TrySound**
Found an issue in my editor after sending form (serialize->deseriaize)
newlines after lists are increased.

### CODE REVIEW

**Comment by TrySound** [comment]
Hi @Rosey. Could you take a look if you have some time?

**Comment by TrySound** [comment]
Friendly ping @Rosey

**Comment by TrySound** [comment]
Hi @Rosey Friendly ping

**Comment by chrisrobbins** [comment]
@Rosey Friendly ping here, I know you are very busy. Any chance you can give some info on when you might have some time to take a look at this PR?

**Comment by Rosey** [comment]
sorry team! merging now.

@chrisrobbins thanks for the twitter ping, another maintainer would be useful 😭 The job that I worked where we were using this library I no longer work at so I don't have any work-related excuse to look at this anymore, and not any personal time either 😓 

Anything to do with newline behaviour I am wary of merging without testing super carefully because I find it's a finicky area and every bug fix seems to introduce a different bug 😛  I kind of regret adding support for it 😆 Merged this one because it seems fairly straightfoward though 🙂

**Comment by TrySound** [comment]
Thank you Rose

**Comment by chrisrobbins** [comment]
Thank you!

**Pull request merged**
