### PR TITLE
Off by one fix for preserveNewlines

### PR DESCRIPTION
**Pull request by danielsnider**
To fix issue #111

### CODE REVIEW

**Comment by Rosey** [comment]
Just been testing a bit 🙂 It seems mostly good, I'm a bit nervous about the addition of `+ 1` and some of the logic changes because I don't fully understand the change I think 😳  I wrote this test, which passes in master but fails here -

```javascript
  it('renders blockquotes correctly', function () {
    var markdownString = '> Hello I am Blockquote\n\nI am not\n\n> I am';
    var draftJSObject = markdownToDraft(markdownString, {preserveNewlines: true});
    var markdownFromDraft = draftToMarkdown(draftJSObject, {preserveNewlines: true});
    expect(markdownFromDraft).toEqual(markdownString);
  });
```

An extra newline is being added in this branch which throws off the idempotency - 

Screen Shot 2020-01-28 at 9 04 38 AM

**Comment by danielsnider** [comment]
Thank you for the investigations! I'll try to improve the `+1`.
All the best!

**Comment by Rosey** [comment]
Thanks! Even if that +1 does make sense it may just be that I don't fully understand it, so an explanation might be all that is required, I don't know :) the newline stuff is tricky, since markdown doesn't technically support whitespace like this under normal circumstances

**Comment by danielsnider** [comment]
Hi @Rosey,
I hope you and yours are well. Checkout my commit messages for brief explanations. Let me know what you think. Maybe it all makes sense or maybe we should audio chat to help reach a common understanding.

I'm wondering is it even possible to preserveNewlines with blockquotes and maintain idempotency? I don't think so. This test shows why:
```
  it('fails to be idempotent for blockquotes and preserveNewlines', function () {
    var markdownString = '> Hello I am Blockquote\nI am not';
    var draftJSObject = markdownToDraft(markdownString, {preserveNewlines: true});
    var markdownFromDraft = draftToMarkdown(draftJSObject, {preserveNewlines: true});
    expect(markdownFromDraft).toEqual(markdownString);
  });
```
image

**Comment by Rosey** [comment]
Thanks very much for all your work on this, that makes sense 🙂

**Pull request merged**
